projects:
- id: lineage-m
  label: 리니지M
  enabled: true
  titles:
  - 리니지m방
  update_notes_url: https://lineagem.plaync.com/board/update/list
  email:
    sender: muktop@ncsoft.com
    receivers:
    - muktop@ncsoft.com
- id: aion2
  label: 아이온2
  enabled: true
  titles:
  - 센터로드 아이온2
  update_notes_url: https://aion2.plaync.com/ko-kr/board/update/list
  email:
    sender: muktop@ncsoft.com
    receivers:
    - muktop@ncsoft.com
- id: lineage-classic
  label: 리니지클래식
  enabled: true
  titles:
  - 리니지 클래식 이실로테 소통방
  update_notes_url: https://lineageclassic.plaync.com/ko-kr/board/update/list
  email:
    sender: muktop@ncsoft.com
    receivers:
    - muktop@ncsoft.com
- id: 리니지2m
  label: l2m
  enabled: true
  titles:
  - 리니지2M플펀
  update_notes_url: https://lineage2m.plaync.com/board/update/list
  email:
    sender: muktop@ncsoft.com
    receivers:
    - muktop@ncsoft.com
exclude_nicks:
- 오픈채팅봇
exclude_body_patterns:
- 사진
- 이모티콘
- 삭제된 메시지
